spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mobile_dev
        username: dev_user
        password: Passw0rd
    jpa:
        hibernate:
            ddl-auto: validate
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: mysql
        show-sql: true